# Site settings
title: Jekyll-Uno
description: 'Welcome to the blog of Meredith Broadway'
url: 'http://broadwym.github.io'
baseurl: '/jekyll-uno'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Meredith Broadway'
  email: meredith.broadway@owen.vanderbilt.edu
  twitter_username: broadwym
  github_username:  broadwym
  linkedin_username:  meredith-broadway-168a4b43

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
